import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import StaffNavbar from '../../components/StaffNavbar';
import ProfileHeader    from '../../components/profile/ProfileHeader';
import StudentInfoCard  from '../../components/profile/StudentInfoCard';
import AcademicInfoCard from '../../components/profile/AcademicInfoCard';
import ProfileActions   from '../../components/profile/ProfileActions';
import ComingSoonCard   from '../../components/profile/ComingSoonCard';
import AccessibilityProfileCard from '../../components/profile/AccessibilityProfileCard';
import { getStudentProfile, updateStudentProfile, getTeacherClasses } from '../../services/api';
import {
  AlertCircle, Loader2, RefreshCw,
  Accessibility, ClipboardList, TrendingUp, Sparkles
} from 'lucide-react';

// ── Sidebar module definitions (Phase 2+) ─────────────────────
const COMING_SOON_MODULES = [
  {
    icon: ClipboardList,
    title: 'Assessment History',
    description: 'Full history of completed assessments, prelims results, and score trends over time.',
    accentColor: 'purple',
  },
  {
    icon: TrendingUp,
    title: 'Learning Progress',
    description: 'XP earned, streak data, completed game levels and classroom engagement metrics.',
    accentColor: 'emerald',
  },
  {
    icon: Sparkles,
    title: 'AI Recommendations',
    description: 'Personalised learning suggestions generated by ACLC\'s cognitive adaptability engine.',
    accentColor: 'amber',
  },
];

// ── Toast component ────────────────────────────────────────────
const Toast = ({ toast, onClose }) => {
  if (!toast) return null;
  const colorMap = {
    success: 'bg-emerald-600 border-emerald-400/50 shadow-emerald-500/20',
    error:   'bg-red-600   border-red-400/50   shadow-red-500/20',
    info:    'bg-blue-600  border-blue-400/50  shadow-blue-500/20',
  };
  return (
    <div className="fixed top-20 right-5 z-50 animate-fade-in-up">
      <div className={`flex items-center gap-3 px-5 py-3.5 rounded-2xl border shadow-2xl backdrop-blur-md text-white text-xs font-bold ${colorMap[toast.type] || colorMap.info}`}>
        <span>{toast.message}</span>
        <button onClick={onClose} className="ml-2 hover:opacity-70 text-lg leading-none">×</button>
      </div>
    </div>
  );
};

// ── Loading skeleton ───────────────────────────────────────────
const LoadingSkeleton = () => (
  <div className="space-y-6 animate-pulse">
    <div className="h-40 bg-[var(--bg-surface)] rounded-3xl border border-[var(--border-color)]" />
    <div className="grid lg:grid-cols-3 gap-6">
      <div className="lg:col-span-2 space-y-4">
        <div className="h-56 bg-[var(--bg-surface)] rounded-2xl border border-[var(--border-color)]" />
        <div className="h-56 bg-[var(--bg-surface)] rounded-2xl border border-[var(--border-color)]" />
      </div>
      <div className="space-y-4">
        {[1,2,3,4].map(i => (
          <div key={i} className="h-24 bg-[var(--bg-surface)] rounded-2xl border border-[var(--border-color)]" />
        ))}
      </div>
    </div>
  </div>
);

// ── Main Page ──────────────────────────────────────────────────
const StudentProfile = () => {
  const { studentId } = useParams();
  const navigate      = useNavigate();

  // Data state
  const [student,  setStudent]  = useState(null);
  const [classes,  setClasses]  = useState([]);   // all classes student is enrolled in
  const [allClasses, setAllClasses] = useState([]); // teacher's classes for dropdown

  // UI state
  const [isLoading, setIsLoading] = useState(true);
  const [error,     setError]     = useState(null);
  const [isEditing, setIsEditing] = useState(false);
  const [isSaving,  setIsSaving]  = useState(false);
  const [toast,     setToast]     = useState(null);

  // Controlled form state (mirrors editable fields)
  const [form, setForm] = useState({
    name:        '',
    rollNumber:  '',
    gender:      '',
    dateOfBirth: '',
    phone:       '',
    department:  '',
    year:        '',
    section:     '',
    classroomId: '',
    status:      'Active',
  });

  // ── Show toast helper ──────────────────────────────────────
  const showToast = useCallback((message, type = 'info') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 4000);
  }, []);

  // ── Populate form from student object ──────────────────────
  const populateForm = useCallback((s) => {
    setForm({
      name:        s.name        || '',
      rollNumber:  s.rollNumber  || '',
      gender:      s.gender      || '',
      dateOfBirth: s.dateOfBirth
        ? new Date(s.dateOfBirth).toISOString().split('T')[0]
        : '',
      phone:       s.phone       || '',
      department:  s.department  || '',
      year:        s.year        || '',
      section:     s.section     || '',
      classroomId: s.classroomId?._id || s.classroomId || '',
      status:      s.status      || 'Active',
    });
  }, []);

  // ── Fetch student profile ──────────────────────────────────
  const fetchProfile = useCallback(async () => {
    setIsLoading(true);
    setError(null);
    try {
      const [profileRes, classesRes] = await Promise.all([
        getStudentProfile(studentId),
        getTeacherClasses().catch(() => []),
      ]);

      setStudent(profileRes.student);
      setClasses(profileRes.classes || []);
      // Provide teacher's classes so the dropdown has options
      setAllClasses(Array.isArray(classesRes) ? classesRes : classesRes?.classes || []);
      populateForm(profileRes.student);
    } catch (err) {
      const msg = err.response?.data?.message || err.message || 'Failed to load student profile';
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  }, [studentId, populateForm]);

  useEffect(() => {
    fetchProfile();
  }, [fetchProfile]);

  // ── Auto-dismiss toast on unmount ─────────────────────────
  useEffect(() => () => clearTimeout(), []);

  // ── Form change handler ────────────────────────────────────
  const handleChange = (e) => {
    const { name, value } = e.target;
    setForm(prev => ({ ...prev, [name]: value }));
  };

  // ── Enter edit mode ────────────────────────────────────────
  const handleEdit = () => {
    populateForm(student);  // reset to current saved values
    setIsEditing(true);
  };

  // ── Cancel edit ───────────────────────────────────────────
  const handleCancel = () => {
    populateForm(student);
    setIsEditing(false);
  };

  // ── Save profile ──────────────────────────────────────────
  const handleSave = async () => {
    if (!form.name?.trim()) {
      showToast('Student name is required', 'error');
      return;
    }

    setIsSaving(true);
    try {
      const payload = {
        ...form,
        dateOfBirth: form.dateOfBirth || null,
        classroomId: form.classroomId || null,
      };

      const res = await updateStudentProfile(studentId, payload);
      setStudent(res.student);
      populateForm(res.student);
      setIsEditing(false);
      showToast('Profile updated successfully!', 'success');
    } catch (err) {
      const msg = err.response?.data?.message || err.message || 'Failed to save profile';
      showToast(msg, 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // ── Back navigation ───────────────────────────────────────
  const handleBack = () => navigate('/staff/classes');

  // ── Render ─────────────────────────────────────────────────
  return (
    <div className="min-h-screen bg-[var(--bg-base)] text-[var(--text-primary)] transition-colors duration-300">
      <StaffNavbar />

      {/* Toast */}
      <Toast toast={toast} onClose={() => setToast(null)} />

      <main className="container mx-auto px-4 md:px-8 py-8 max-w-7xl animate-fade-in-up space-y-6">

        {/* ── Page title breadcrumb ── */}
        <div className="flex items-center gap-2 text-xs text-[var(--text-secondary)] font-semibold">
          <button
            onClick={handleBack}
            className="hover:text-[var(--text-primary)] transition-colors"
          >
            My Classes
          </button>
          <span>/</span>
          <span className="text-[var(--text-primary)] font-bold">Student Profile</span>
        </div>

        {/* ── Loading ── */}
        {isLoading && <LoadingSkeleton />}

        {/* ── Error ── */}
        {!isLoading && error && (
          <div className="flex flex-col items-center justify-center py-20 gap-4">
            <div className="w-14 h-14 rounded-full bg-red-500/10 text-red-500 flex items-center justify-center">
              <AlertCircle size={28} />
            </div>
            <p className="text-base font-bold text-[var(--text-primary)]">Failed to load profile</p>
            <p className="text-sm text-[var(--text-secondary)]">{error}</p>
            <button
              onClick={fetchProfile}
              className="flex items-center gap-2 px-5 py-2.5 bg-blue-600 text-white rounded-xl font-bold text-sm hover:bg-blue-700 transition-colors"
            >
              <RefreshCw size={15} /> Retry
            </button>
          </div>
        )}

        {/* ── Main content ── */}
        {!isLoading && !error && student && (
          <>
            {/* Header */}
            <ProfileHeader
              student={student}
              onEdit={handleEdit}
              isEditing={isEditing}
            />

            {/* Two-column layout: main content + sidebar */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">

              {/* ── Left / Main column ── */}
              <div className="lg:col-span-2 space-y-6">

                {/* Section 1 — Student Information */}
                <StudentInfoCard
                  student={student}
                  form={form}
                  isEditing={isEditing}
                  onChange={handleChange}
                />

                {/* Section 2 — Academic Information */}
                <AcademicInfoCard
                  student={student}
                  classes={allClasses}
                  form={form}
                  isEditing={isEditing}
                  onChange={handleChange}
                />

                {/* Section 3 — Accessibility Profile (Phase 2) */}
                <AccessibilityProfileCard
                  studentId={studentId}
                  onShowToast={showToast}
                />

                {/* Action bar */}
                <ProfileActions
                  isEditing={isEditing}
                  isSaving={isSaving}
                  onSave={handleSave}
                  onCancel={handleCancel}
                  onBack={handleBack}
                />

              </div>

              {/* ── Right / Sidebar column ── */}
              <aside className="space-y-4">

                {/* Enrolled classes quick-view */}
                <div className="bg-[var(--bg-surface)] rounded-2xl border border-[var(--border-color)] shadow-sm overflow-hidden">
                  <div className="px-5 py-4 border-b border-[var(--border-color)]">
                    <h3 className="font-extrabold text-sm text-[var(--text-primary)]">Enrolled Classes</h3>
                  </div>
                  <div className="p-4 space-y-2">
                    {classes.length > 0 ? classes.map(cls => (
                      <div
                        key={cls._id}
                        className="flex items-center gap-3 p-3 bg-[var(--bg-base)] rounded-xl border border-[var(--border-color)]"
                      >
                        <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-indigo-500 to-blue-600 text-white font-black text-xs flex items-center justify-center flex-shrink-0">
                          {cls.name[0].toUpperCase()}
                        </div>
                        <div className="min-w-0">
                          <p className="text-xs font-extrabold text-[var(--text-primary)] truncate">{cls.name}</p>
                          <p className="text-[10px] text-[var(--text-secondary)] truncate">{cls.subject}</p>
                        </div>
                      </div>
                    )) : (
                      <p className="text-xs text-[var(--text-secondary)] italic py-2">Not enrolled in any class yet.</p>
                    )}
                  </div>
                </div>

                {/* Gamification snapshot */}
                <div className="bg-gradient-to-br from-indigo-500/10 to-blue-500/10 rounded-2xl border border-indigo-500/20 p-5">
                  <h3 className="font-extrabold text-sm text-indigo-600 dark:text-indigo-400 mb-3">
                    🎮 Gamification Snapshot
                  </h3>
                  <div className="grid grid-cols-3 gap-2 text-center">
                    <div className="bg-white/60 dark:bg-white/5 rounded-xl p-2.5 border border-indigo-200/40">
                      <p className="text-lg font-black text-indigo-600">{student.level || 1}</p>
                      <p className="text-[9px] font-bold text-[var(--text-secondary)] uppercase tracking-wider">Level</p>
                    </div>
                    <div className="bg-white/60 dark:bg-white/5 rounded-xl p-2.5 border border-indigo-200/40">
                      <p className="text-lg font-black text-amber-600">{student.xp || 0}</p>
                      <p className="text-[9px] font-bold text-[var(--text-secondary)] uppercase tracking-wider">XP</p>
                    </div>
                    <div className="bg-white/60 dark:bg-white/5 rounded-xl p-2.5 border border-indigo-200/40">
                      <p className="text-lg font-black text-orange-500">{student.streak || 0}</p>
                      <p className="text-[9px] font-bold text-[var(--text-secondary)] uppercase tracking-wider">Streak</p>
                    </div>
                  </div>
                  <div className="mt-3 flex items-center justify-between text-[11px]">
                    <span className="text-[var(--text-secondary)] font-semibold">Prelims</span>
                    <span className={`font-extrabold ${student.isPrelimsCompleted ? 'text-emerald-600' : 'text-amber-600'}`}>
                      {student.isPrelimsCompleted ? `Completed · ${student.prelimsScore}%` : 'Not completed'}
                    </span>
                  </div>
                </div>

                {/* Divider label */}
                <div className="flex items-center gap-3">
                  <div className="flex-1 h-px bg-[var(--border-color)]" />
                  <span className="text-[10px] font-extrabold text-[var(--text-secondary)] uppercase tracking-widest whitespace-nowrap">
                    Future Modules
                  </span>
                  <div className="flex-1 h-px bg-[var(--border-color)]" />
                </div>

                {/* Coming Soon cards */}
                {COMING_SOON_MODULES.map(mod => (
                  <ComingSoonCard key={mod.title} {...mod} />
                ))}

              </aside>
            </div>
          </>
        )}
      </main>
    </div>
  );
};

export default StudentProfile;
